[package]
name = "fire_fx"
version = "0.1.0"
authors = ["Ryan Blecher <notryanb@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6.3"

[dependencies.sdl2]
version = "0.32.1"
default-features = false
features = ["image"]
